name: 🐞 Bug Report
description: Tell us about something that's not working the way we (probably) intend.
labels: ["Type: Bug"]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have checked for existing issues https://github.com/getsentry/profiling-browser/issues
          required: true
        - label: I have reviewed the documentation https://docs.sentry.io/
          required: true
        - label: I am using the latest SDK release https://github.com/getsentry/profiling-browser/releases
          required: true
  - type: dropdown
    id: type
    attributes:
      label: How do you use Sentry?
      options:
        - Sentry Saas (sentry.io)
        - Self-hosted/on-premise
    validations:
      required: true
  - type: input
    id: sdk-version
    attributes:
      label: SDK Version
      description: What version of the SDK are you using?
      placeholder: ex. 1.0.0
    validations:
      required: true
  - type: input
    id: link-to-sentry
    attributes:
      label: Link to Sentry event
      description: If applicable, provide a link to the affected event from your Sentry account. The event will only be viewable by Sentry staff.
      placeholder: https://sentry.io/organizations/<org-slug>/issues/<issue-id>/events/<event-id>/?project=<project-id>    
  - type: textarea
    id: deploy
    attributes:
      label: How is your code deployed and bundled?
      description: Are you installing the dependencies on remote (postinstall is required to run so bindings compile) or bundling the code and trying to upload as a single index.js file?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      description: How can we see what you're seeing? Specific is terrific.
      placeholder: |-
        1. What
        2. you
        3. did.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Result
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Result
      description: Logs? Screenshots? Yes, please.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |-
        ## Thanks 🙏
